INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD
include (util/util.pri)
include (algorithm/algorithm.pri)
include (asic/asic.pri)
include (socket/socket.pri)
include (qrencode/qrencode.pri)
include (convert/convert.pri)
include (serial/serial.pri)
include (zprinter/zPrinter.pri)
include (PropertyPage/PropertyPage.pri)
include (HttpServer/HttpServer.pri)
include (halcon/halcon.pri)
include (log4cpp/log4cpp.pri)
include (burning/burning.pri)
