/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104569-g08b4716a9e-20211116"
#endif /* AVUTIL_FFVERSION_H */
