#ifndef ALGCONST_H
#define ALGCONST_H

#include <QObject>

static QStringList g_expertList = {"rasel", "int", "gain", "hssd", "gfid",
                                   "rc", "rd", "refrd", "snsadj", "sgrsadj",
                                   "vbus", "gskop2", "nmiddle", "nmiddlegsize",
                                   "rampcap", "pllm", "nmin", "csize"};

struct IspItemInfo {
    QString name;
    int word;
    bool isUnsigned;
};

struct IspComboInfo {
    int index;
    QList<IspItemInfo> list;
    QString dec;
};

static QList<IspItemInfo> g_abcMap = {
    {"ab_en", 1, true},
    {"ab_u16AbcTh1", 2, true},
    {"ab_u16AbcTh2", 2, true},
};

static QList<IspItemInfo> g_bprMap = {
    {"bpr_en", 1, true},
    {"bpr_bAutoEn", 1, true},
    {"bpr_u32AutoThr", 4, true},
    {"bpr_u32FramNum", 4, true},
    {"bpr_bKCompEn", 1, true},
    {"bpr_u16MaxTh", 2, true},
    {"bpr_u16MinTh", 2, true},
    {"bpr_bManualEn", 1, true},
    {"bpr_s32X", 4, true},
    {"bpr_s32Y", 4, true},
    {"bpr_au16Col", 2, true},
};

static QList<IspItemInfo> g_nr3dMap = {
    {"nr3draw_en", 1, true},
    {"nr3draw_u8AddDfAlpha", 1, true},
    {"nr3draw_u8AddDfFilter", 1, true},
    {"nr3draw_u16AlphaMax", 2, true},
    {"nr3draw_u16Motion", 2, true},
    {"nr3draw_u8AlphaRatio", 1, true},
    {"nr3draw_u8DfFilterH", 1, true},
    {"nr3draw_u8DfFilterV", 1, true},
    {"nr3draw_au8DiffIirCoef0", 1, true},
    {"nr3draw_au8DiffIirCoef1", 1, true},
    {"nr3draw_u16DiffIirTh", 2, true},
    {"nr3draw_au8GsCoef0", 1, true},
    {"nr3draw_au8GsCoef1", 1, true},
    {"nr3draw_au8GsCoef2", 1, true},
    {"nr3draw_u8GsFilterWinSel", 1, true},
    {"nr3draw_u16GAlphaMax", 2, true},
    {"nr3draw_u8GBlendingRatio", 1, true},
    {"nr3draw_au8TailCoef0", 1, true},
    {"nr3draw_au8TailCoef1", 1, true},
    {"nr3draw_u16TailTh", 2, true},
};

static QList<IspItemInfo> g_sffcMap = {
    {"sffc_en", 1, true},
    {"sffc_enUpdateFrmNum", 1, true},
    {"sffc_u16SffcThr", 2, true},
    {"sffc_u8SffcStep", 1, true},
};

static QList<IspItemInfo> g_sffcMap2 = {
    {"sffc_en", 1, true},
    {"sffc_enUpdateFrmNum", 1, true},
    {"sffc_u16SffcThr", 2, true},
    {"sffc_u8SffcStep", 1, true},
    {"sffc_bRealbestCfgEn", 1, true},
    {"sffc_u16Realbest", 2, true},
};

static QList<IspItemInfo> g_fpncMap = {
    {"fpnc_en", 1, true},
    {"fpnc_u16NoiseModifiedCoef", 2, true},
    {"fpnc_u8NoiseClip", 1, true},
    {"fpnc_u8NoiseSmoothStep", 1, true},
    {"fpnc_u16Num1Thr", 2, true},
    {"fpnc_u8Num2Thr", 1, true},
    {"fpnc_u16AdaptWeightCoef", 2, true},
    {"fpnc_u16AdaptWeightThr", 2, true},
    {"fpnc_u16WeightThr", 2, true},
};

static QList<IspItemInfo> g_dnsMap = {
    {"dns_en", 1, true},
    {"dns_au16Slope0", 2, true},
    {"dns_au16Slope1", 2, true},
    {"dns_au16Th0", 2, true},
    {"dns_au16Th1", 2, true},
    {"dns_au16Th10", 2, true},
    {"dns_au16Th11", 2, true},
    {"dns_au16Th20", 2, true},
    {"dns_au16Th21", 2, true},
    {"dns_au8Ratio0", 1, true},
    {"dns_au8Ratio1", 1, true},
};

static QList<IspItemInfo> g_drcMap = {
    {"drc_au8ContrastLv0", 1, true},
    {"drc_au8ContrastLv1", 1, true},
    {"drc_au8ContrastLv2", 1, true},
    {"drc_au8ContrastTh0", 1, true},
    {"drc_au8ContrastTh1", 1, true},
    {"drc_au8ContrastTh2", 1, true},
    {"drc_au8ContrastTh3", 1, true},
    {"drc_s32BeginX", 4, true},
    {"drc_s32BeginY", 4, true},
    {"drc_s32EndX", 4, true},
    {"drc_s32EndY", 4, true},
    {"drc_au8Gs0Coef0", 1, true},
    {"drc_au8Gs0Coef1", 1, true},
    {"drc_au8Gs0Coef2", 1, true},
    {"drc_au8Gs1Coef0", 1, true},
    {"drc_au8Gs1Coef1", 1, true},
    {"drc_au8Gs1Coef2", 1, true},
    {"drc_u8GsMode", 1, true},
    {"drc_enHistmaxSel", 1, true},
    {"drc_u32HistmaxExtValue", 4, true},
    {"drc_u32HistmaxHighTh", 4, true},
    {"drc_u32HistmaxLowTh", 4, true},
    {"drc_au8LumLv0", 1, true},
    {"drc_au8LumLv1", 1, true},
    {"drc_au8LumLv2", 1, true},
    {"drc_au8LumTh0", 1, true},
    {"drc_au8LumTh1", 1, true},
    {"drc_au8LumTh2", 1, true},
    {"drc_au8LumTh3", 1, true},
    {"drc_au16VarTh0", 2, true},
    {"drc_au16VarTh1", 2, true},
    {"drc_au16VarTh2", 2, true},
    {"drc_au16VarTh3", 2, true},
    {"drc_au8VarLv0", 1, true},
    {"drc_au8VarLv1", 1, true},
    {"drc_au8VarLv2", 1, true},
    {"drc_u16ExternalContrast", 2, true},
    {"drc_u16ExternalLuma", 2, true},
    {"drc_u16Hf", 2, true},
    {"drc_u16Step", 2, true},
    {"drc_u32LeftPointTh", 4, true},
    {"drc_u32RightPointTh", 4, true},
    {"drc_u8Ssoval", 1, true},
};

static QList<IspItemInfo> g_drcMap2 = {
    {"drc_au8ContrastLv0", 1, true},
    {"drc_au8ContrastLv1", 1, true},
    {"drc_au8ContrastLv2", 1, true},
    {"drc_au8ContrastTh0", 1, true},
    {"drc_au8ContrastTh1", 1, true},
    {"drc_au8ContrastTh2", 1, true},
    {"drc_au8ContrastTh3", 1, true},
    {"drc_s32BeginX", 4, true},
    {"drc_s32BeginY", 4, true},
    {"drc_s32EndX", 4, true},
    {"drc_s32EndY", 4, true},
    {"drc_au8Gs0Coef0", 1, true},
    {"drc_au8Gs0Coef1", 1, true},
    {"drc_au8Gs0Coef2", 1, true},
    {"drc_au8Gs1Coef0", 1, true},
    {"drc_au8Gs1Coef1", 1, true},
    {"drc_au8Gs1Coef2", 1, true},
    {"drc_u8GsMode", 1, true},
    {"drc_enHistmaxSel", 1, true},
    {"drc_u32HistmaxExtValue", 4, true},
    {"drc_u32HistmaxHighTh", 4, true},
    {"drc_u32HistmaxLowTh", 4, true},
    {"drc_au8LumLv0", 1, true},
    {"drc_au8LumLv1", 1, true},
    {"drc_au8LumLv2", 1, true},
    {"drc_au8LumTh0", 1, true},
    {"drc_au8LumTh1", 1, true},
    {"drc_au8LumTh2", 1, true},
    {"drc_au8LumTh3", 1, true},
    {"drc_au16VarTh0", 2, true},
    {"drc_au16VarTh1", 2, true},
    {"drc_au16VarTh2", 2, true},
    {"drc_au16VarTh3", 2, true},
    {"drc_au8VarLv0", 1, true},
    {"drc_au8VarLv1", 1, true},
    {"drc_au8VarLv2", 1, true},
    {"drc_u16ExternalContrast", 2, true},
    {"drc_u16ExternalLuma", 2, true},
    {"drc_u16Hf", 2, true},
    {"drc_u16Step", 2, true},
    {"drc_u32LeftPointTh", 4, true},
    {"drc_u32RightPointTh", 4, true},
    {"drc_u8Ssoval", 1, true},
    {"drc_enGrayMaxMinMode", 1, true},
    {"drc_u16GrayMinVal", 2, true},
    {"drc_u16GrayMaxVal", 2, true},
    {"drc_au16PseudoColorY160", 2, true},
    {"drc_au16PseudoColorY161", 2, true},
};

static QList<IspItemInfo> g_eeMap = {
    {"ee_en", 1, true},
    {"ee_u8FreqR1", 1, true},
    {"ee_u8FreqR2", 1, true},
    {"ee_u8FreqR3", 1, true},
    {"ee_u8FreqT1", 1, true},
    {"ee_u8FreqT2", 1, true},
    {"ee_u8FreqT3", 1, true},
    {"ee_u8FreqT4", 1, true},
    {"ee_u8LumR1", 1, true},
    {"ee_u8LumR2", 1, true},
    {"ee_u8LumR3", 1, true},
    {"ee_u8LumT1", 1, true},
    {"ee_u8LumT2", 1, true},
    {"ee_u8LumT3", 1, true},
    {"ee_u8LumT4", 1, true},
    {"ee_u8ThinAddR1", 1, true},
    {"ee_u8ThinAddR2", 1, true},
    {"ee_u8ThinAddR3", 1, true},
    {"ee_u8ThinAddT1", 1, true},
    {"ee_u8ThinAddT2", 1, true},
    {"ee_u8ThinAddT3", 1, true},
    {"ee_u8ThinAddT4", 1, true},
    {"ee_u8ThinPowerR1", 1, true},
    {"ee_u8ThinPowerR2", 1, true},
    {"ee_u8ThinPowerR3", 1, true},
    {"ee_u8ThinPowerT1", 1, true},
    {"ee_u8ThinPowerT2", 1, true},
    {"ee_u8ThinPowerT3", 1, true},
    {"ee_u8ThinPowerT4", 1, true},
    {"ee_u8WidthR1", 1, true},
    {"ee_u8WidthR2", 1, true},
    {"ee_u8WidthR3", 1, true},
    {"ee_u8WidthT1", 1, true},
    {"ee_u8WidthT2", 1, true},
    {"ee_u8WidthT3", 1, true},
    {"ee_u8WidthT4", 1, true},
    {"ee_u8EdgeSmooth", 1, true},
    {"ee_u8FltWinMode", 1, true},
    {"ee_u8NegClipRatio", 1, true},
    {"ee_u8NegMinOffset", 1, true},
    {"ee_u8NegStr", 1, true},
    {"ee_u8OffsetStrength", 1, true},
    {"ee_u8PosClipRatio", 1, true},
    {"ee_u8PosMaxOffset", 1, true},
    {"ee_u8PosStr", 1, true},
    {"ee_u8WidthRatio", 1, true},
};

static QList<IspItemInfo> g_eeMap2 = {
    {"ee_en", 1, true},
    {"ee_u8FreqR1", 1, true},
    {"ee_u8FreqR2", 1, true},
    {"ee_u8FreqR3", 1, true},
    {"ee_u8FreqT1", 1, true},
    {"ee_u8FreqT2", 1, true},
    {"ee_u8FreqT3", 1, true},
    {"ee_u8FreqT4", 1, true},
    {"ee_u8LumR1", 1, true},
    {"ee_u8LumR2", 1, true},
    {"ee_u8LumR3", 1, true},
    {"ee_u8LumT1", 1, true},
    {"ee_u8LumT2", 1, true},
    {"ee_u8LumT3", 1, true},
    {"ee_u8LumT4", 1, true},
    {"ee_u8ThinAddR1", 1, true},
    {"ee_u8ThinAddR2", 1, true},
    {"ee_u8ThinAddR3", 1, true},
    {"ee_u8ThinAddT1", 1, true},
    {"ee_u8ThinAddT2", 1, true},
    {"ee_u8ThinAddT3", 1, true},
    {"ee_u8ThinAddT4", 1, true},
    {"ee_u8ThinPowerR1", 1, true},
    {"ee_u8ThinPowerR2", 1, true},
    {"ee_u8ThinPowerR3", 1, true},
    {"ee_u8ThinPowerT1", 1, true},
    {"ee_u8ThinPowerT2", 1, true},
    {"ee_u8ThinPowerT3", 1, true},
    {"ee_u8ThinPowerT4", 1, true},
    {"ee_u8WidthR1", 1, true},
    {"ee_u8WidthR2", 1, true},
    {"ee_u8WidthR3", 1, true},
    {"ee_u8WidthT1", 1, true},
    {"ee_u8WidthT2", 1, true},
    {"ee_u8WidthT3", 1, true},
    {"ee_u8WidthT4", 1, true},
    {"ee_u8EdgeSmooth", 1, true},
    {"ee_u8NegClipRatio", 1, true},
    {"ee_u8NegMinOffset", 1, true},
    {"ee_u8NegStr", 1, true},
    {"ee_u8OffsetStrength", 1, true},
    {"ee_u8PosClipRatio", 1, true},
    {"ee_u8PosMaxOffset", 1, true},
    {"ee_u8PosStr", 1, true},
    {"ee_u8WidthRatio", 1, true},
    {"ee_bClipEn", 1, true},
    {"ee_bConsMode", 1, true},
    {"ee_u8ContrastR1", 1, true},
    {"ee_u8ContrastR2", 1, true},
    {"ee_u8ContrastR3", 1, true},
    {"ee_u8ContrastT1", 1, true},
    {"ee_u8ContrastT2", 1, true},
    {"ee_u8ContrastT3", 1, true},
    {"ee_u8ContrastT4", 1, true},
    {"ee_u8LightHigh", 1, true},
    {"ee_u8OffsetThrd", 1, true},
    {"ee_u8LightNumLow", 1, true},
    {"ee_u8LightNumHigh", 1, true},
};

static QList<IspItemInfo> g_lwdrMap = {
    {"lwdr_en", 1, true},
    {"lwdr_au16GausCoef0", 2, true},
    {"lwdr_au16GausCoef1", 2, true},
    {"lwdr_au16GausCoef2", 2, true},
    {"lwdr_au16GausCoef3", 2, true},
    {"lwdr_au16GausCoef4", 2, true},
    {"lwdr_bLwdrFusEn", 1, true},
    {"lwdr_u16FusTh", 2, true},
    {"lwdr_u16NoiseAlpha", 2, true},
    {"lwdr_u8AlphaCofe", 1, true},
    {"lwdr_u8FusCoef", 1, true},
    {"lwdr_u8GlobalLuma", 1, true},
    {"lwdr_u8NoiseLevel", 1, true},
    {"lwdr_u8PWeight", 1, true},
};

static QList<IspItemInfo> g_lwdrMap2 = {
    {"lwdr_en", 1, true},
    {"lwdr_u8ScaleRatio", 1, true},
    {"lwdr_u8GLuma", 1, true},
    {"lwdr_u8Gontrast", 1, true},
    {"lwdr_u16NoiseLevel", 2, true},
    {"lwdr_bFusEnable", 1, true},
    {"lwdr_u16FusDelta", 2, true},
    {"lwdr_u16FusThrhd", 2, true},
    {"lwdr_u8AlphaFusCofe", 1, true},
    {"lwdr_u16AlphaTabLen", 2, true},
    {"lwdr_u8DsFltAlpha", 1, true},
    {"lwdr_u8DsFltSize", 1, true},
    {"lwdr_u8DsLegFltAlpha", 1, true},
    {"lwdr_au8GsCoef0", 1, true},
    {"lwdr_au8GsCoef1", 1, true},
    {"lwdr_au8GsCoef2", 1, true},
    {"lwdr_au8GsCoef3", 1, true},
    {"lwdr_au8GsCoef4", 1, true},
    {"lwdr_u16FiTabLen", 2, true},
};

static QList<IspItemInfo> g_rfcMap = {
    {"rfc_en", 1, true},
    {"rfc_au16NumTh0", 2, true},
    {"rfc_au16NumTh1", 2, true},
    {"rfc_au16NumTh2", 2, true},
    {"rfc_au32RowDiffTh0", 4, true},
    {"rfc_au32RowDiffTh1", 4, true},
    {"rfc_bRfcSumMode", 1, true},
    {"rfc_u8InterFrameTh", 1, true},
    {"rfc_u8IntraFrameTh", 1, true},
    {"rfc_u8CutThr", 1, true},
    {"rfc_u8FilterSel", 1, true},
    {"rfc_u8LumFixRate", 1, true},
    {"rfc_u8NoiseThr", 1, true},
};

static QList<IspItemInfo> g_bacaMap = {
    {"baca_bBacaEn", 1, true},
    {"baca_u8ContrastParam", 1, true},
    {"baca_u8LumParam", 1, true},
    {"baca_au8RatioT0", 1, true},
    {"baca_au8RatioT1", 1, true},
    {"baca_au8RatioT2", 1, true},
    {"baca_au8RatioT3", 1, true},
    {"baca_au8RatioR0", 1, true},
    {"baca_au8RatioR1", 1, true},
    {"baca_au8RatioR2", 1, true},
    {"baca_u8MeanStep", 1, true},
    {"baca_u8MeanClipMin", 1, true},
    {"baca_u8MeanClipMax", 1, true},
};

static QList<IspItemInfo> g_lbtMap = {
    {"lbt_bLbtEn", 1, true},
    {"lbt_bUpdateNew", 1, true},
    {"lbt_u16LbtStep", 2, true},
    {"lbt_au8ClipLimit0", 1, true},
    {"lbt_au8ClipLimit1", 1, true},
    {"lbt_au8ClipLimit2", 1, true},
    {"lbt_au8ClipLimit3", 1, true},
    {"lbt_au8ClipLimit4", 1, true},
    {"lbt_au8ClipLimit5", 1, true},
    {"lbt_au8ClipLimit6", 1, true},
    {"lbt_au8ClipLimit7", 1, true},
    {"lbt_au8ClipLimit8", 1, true},
    {"lbt_u8BonusSel", 1, true},
    {"lbt_u8BlockCor", 1, true},
};

static QList<IspItemInfo> g_nucMap = {
    {"nuc_bNucEn", 1, true},
    {"nuc_enWorkMode", 1, true},
    {"nuc_enMeanSel", 1, true},
    {"nuc_u16ExtMeanData", 2, true},
    {"nuc_enStatisticsFrmNum", 1, true},
    {"nuc_enStatisticsTemp", 1, true},
    {"nuc_bDeltabStatistics", 1, true},
    {"nuc_s16Coef", 2, false},
};

static QList<IspItemInfo> g_histMap = {
    {"hist_bHistEn", 1, true},
    {"hist_enHistSrcSel", 1, true},
};


static QList<IspComboInfo> g_algIndexList = {
    {0, g_abcMap, "abc"},
    {1, g_bprMap, "bpr"},
    {2, g_nr3dMap, "nr3d"},
    {3, g_sffcMap, "sffc"},
    {4, g_fpncMap, "fpnc"},
    {5, g_rfcMap, "rfc"},
    {6, g_drcMap, "drc"},
    {7, g_eeMap, "ee"},
    {8, g_lwdrMap, "lwdr"},
    {9, g_dnsMap, "dns0"},
    {10, g_dnsMap, "dns1"},
    {11, g_dnsMap, "dns2"},
};

static QList<IspComboInfo> g_algIndexList2 = {
    {0, g_abcMap, "abc"},
    {1, g_bprMap, "bpr"},
    {2, g_nr3dMap, "nr3d"},
    {3, g_sffcMap2, "sffc"},
    {4, g_fpncMap, "fpnc"},
    {5, g_rfcMap, "rfc"},
    {6, g_drcMap2, "drc"},
    {7, g_eeMap2, "ee"},
    {8, g_lwdrMap2, "lwdr"},
    {9, g_dnsMap, "dns0"},
    {10, g_dnsMap, "dns1"},
//    {11, g_dnsMap, "dns2"},
    {12, g_bacaMap, "baca"},
    {13, g_lbtMap, "lbt"},
    {14, g_nucMap, "nuc"},
    {15, g_histMap, "hist"},
};

#endif // ALGCONST_H
