#ifndef MESSAGEID_H
#define MESSAGEID_H

#include <QMap>

#define MSG_ID_MAX 2000

#define ERROR_SUCCEED  0
#define ERROR_INVALID_MSG -1
#define ERROR_INVALID_ID -2
#define ERROR_BAD_POINT_ERROR -3
#define ERROR_BAD_POINT_LIST_ERROR -4

enum UPDATE_FILE_TYPE {
    UPDATE_FILE_ASIC_APP = 0,
    UPDATE_FILE_ARM_APP,
    UDPATE_FILE_ASIC_PATTLE
};

enum MESSAGE_ID_CUSTOM_PAGE {
    MESSAGE_ID_CUSTOM_STATE = 1000,  // 工作状态
    MESSAGE_ID_CUSTOM_GET_VERSION,
    MESSAGE_ID_CUSTOM_SET_TIME,
    MESSAGE_ID_CUSTOM_MANUL_CALIB_EX,
    MESSAGE_ID_CUSTOM_VIDEO_INFO,
    MESSAGE_ID_CUSTOM_UPDATE_INFO,
    MESSAGE_ID_MRTD_SWITCH,
    MESSAGE_ID_ASIC_ALGORITHM,
    MESSAGE_ID_SENSOR_CFG,
    MESSAGE_ID_NVS_INFO,
    MESSAGE_ID_CUSTOM_ROAD_CALIB_EX,
    MESSAGE_ID_CLEAR_AGE_ERROR_CODE,
    MESSAGE_ID_GET_AGE_ERROR_CODE,
    MESSAGE_ID_CLEAR_SENSOR_ERROR_CODE,
    MESSAGE_ID_GET_SENSOR_ERROR_CODE,

    MESSAGE_ID_CUSTOM_I2C_WRITE = 1500,
    MESSAGE_ID_CUSTOM_I2C_READ,
    MESSAGE_ID_CUSTOM_UART_WRITE,
    MESSAGE_ID_CUSTOM_UART_READ,
    MESSAGE_ID_CUSTOM_UPDATE_RESULT,
    MESSAGE_ID_CUSTOM_SET_FPS = 2000
};


// 系统信息
enum MESSAGE_ID_GET_SYS_PAGE {
    MESSAGE_ID_GET_PRODUCT_TYPE = 0,
    MESSAGE_ID_GET_SYS_SOFT_WARE_VERSION,               // 软件版本号
    MESSAGE_ID_GET_SYS_HARD_WARE_VERSION,               // 硬件版本号
    MESSAGE_ID_SYS_SCREEN_RATIO,      // 分辨率
    MESSAGE_ID_SYS_FRAME_RATE,         // 帧率
    MESSAGE_ID_SYS_SN,                        // SN号
    MESSAGE_ID_SYS_DEBUG_MODE,
    MESSAGE_ID_GET_SYS_BOOT_VERSION,
    MESSAGE_ID_GET_SYS_APP_LOAD,
    MESSAGE_ID_GET_SYS_APP_WRITE,
    MESSAGE_ID_GET_SYS_DEV_MODE,
};

// 设置控制页面
enum MESSAGE_ID_OPERATE_PAGE {
    MESSAGE_ID_OPERATE_SAVE = 101,    // 保存设置
    MESSAGE_ID_OPERATE_RESET,           // 恢复出厂
    MESSAGE_ID_OPERATE_SHUTTER,       // 快门控制 0关 1开
    MESSAGE_ID_OPERATE_HEATING,        // 加热片模式 0关 1开
    MESSAGE_ID_OPERATE_HEAT_TEMP,   // 加热片NTC温度
    MESSAGE_ID_OPERATE_AUTO_COMP_ENABLE,  // 自动补偿开关
    MESSAGE_ID_OPERATE_AUTO_COMP_TIME,      // 自动补偿时间
    MESSAGE_ID_OPERATE_CHANGE_VIDEO_FORMAT,   // 图像数据格式
    MESSAGE_ID_OPERATE_ENHANCE_GRADE,
    MESSAGE_ID_OPERATE_BIG_RING_TEMP,
    MESSAGE_ID_OPERATE_BOTTOM_TEMP
};

// 视频设置页
enum MESSAGE_ID_VIDEO_PAGE {
    MESSAGE_ID_VIDEO_PATTLE = 201,    // 伪彩类型
    MESSAGE_ID_VIDEO_FREEZE,              // 图像定格
    MESSAGE_ID_VIDEO_TEST,                 // 测试画面
};

// 图像校正页
enum MESSAGE_ID_ADJUST_IMG_PAGE {
    MESSAGE_ID_ADJUST_IMG_SCENE_COMP = 301,  // 场景补偿
    MESSAGE_ID_ADJUST_IMG_SHUTTER_COMP,         // 快门补偿
    MESSAGE_ID_ADJUST_IMG_MANUL_NUC,              // NUC
    MESSAGE_ID_ADJUST_IMG_SCENE_NUC,               // 场景NUC
    MESSAGE_ID_ADJUST_IMG_BL_COMP,                   // BL补偿
    MESSAGE_ID_ADJUST_IMG_BH_COMP,                  // BH补偿
    MESSAGE_ID_ADJUST_IMG_CALCULATE_K,            // 计算K
    MESSAGE_ID_ADJUST_IMG_SAVE_K,                      // 保存K
    MESSAGE_ID_ADJUST_IMG_LOAD_K,                     // 加载K
    MESSAGE_ID_ADJUST_IMG_LOAD_DEFAULT_K,       // 加载初K
    MESSAGE_ID_ADJUST_IMG_SFFC_ENABLE,             // SFFC使能
    MESSAGE_ID_ADJUST_IMG_SFFC_COLLECT,           // SFFC采集
    MESSAGE_ID_ADJUST_IMG_SFFC_SAVE,                 // SFFC保存
    MESSAGE_ID_ADJUST_IMG_SFFC_LOAD,                 // SFFC加载
    MESSAGE_ID_ADJUST_IMG_CURRENT_POINT,          // 设置光标X Y
    MESSAGE_ID_ADJUST_IMG_ADD_BAD_POINT,          // 添加坏点
    MESSAGE_ID_ADJUST_IMG_DELETE_BAD_POINT,      // 删除坏点
    MESSAGE_ID_ADJUST_IMG_SAVE_BAD_POINT,         // 保存坏点
    MESSAGE_ID_ADJUST_IMG_DELETE_CURRENT_BAD_POINT,  // 删除当前坏点
    MESSAGE_ID_ADJUST_IMG_Y16_BAD_POINT,           // Y16一键校坏点
    MESSAGE_ID_ADJUST_IMG_K_BAD_POINT,               // K值一键校坏点
    MESSAGE_ID_ADJUST_IMG_BAD_POINTS_COUNT,     // 查询坏点个数
};

// 图像算法配置页
enum MESSAGE_ID_ALGORITHM_PAGE {
    MESSAGE_ID_ALGORITHM_CLOSE_ALL = 401,        // 一健开关所有算法
    MESSAGE_ID_ALGORITHM_REDUCE_BAD_POINT,     // 去坏点算法
    MESSAGE_ID_ALGORITHM_EDGE_ENHANCE,           // 边缘增强算法
    MESSAGE_ID_ALGORITHM_CONTRAST_ENHANCE,   // 对比度增强
    MESSAGE_ID_ALGORITHM_REDUCE_LID,                 // 去锅盖算法
    MESSAGE_ID_ALGORITHM_REDUCE_SPACE_NOISE, // 空域降噪算法
    MESSAGE_ID_ALGORITHM_REDUCE_V_GRAIN,         // 去竖纹算法
    MESSAGE_ID_ALGORITHM_REDUCE_H_GRAIN,         // 去横纹算法
    MESSAGE_ID_ALGORITHM_REDUCE_Y16_3D_NOISE, // y16 3D去噪
    MESSAGE_ID_ALGORITHM_REDUCE_Y8_3D_NOISE,   // y8 3D去噪
};

enum MESSAGE_ID_ALGORITHM_VALUE_PAGE {
    MESSAGE_ID_ALGORITHM_BRIGHTNESS_VALUE = 501,  // 亮度调整
    MESSAGE_ID_ALGORITHM_CONTRAST_VALUE,                // 对比度调整
    MESSAGE_ID_ALGORITHM_DETAILS_VALUE,                    // 细节增益
    MESSAGE_ID_ALGORITHM_NO_LINEAR_DIM_VALUE,        // 非线性调光系数
    MESSAGE_ID_ALGORITHM_WIDE_VALUE,                         // 宽动态
    MESSAGE_ID_ALGORITHM_SHARPNESS_1,                           // 边缘增强1
    MESSAGE_ID_ALGORITHM_SHARPNESS_2,                           // 边缘增强2
    MESSAGE_ID_ALGORITHM_SHARPNESS_3,                           // 边缘增强3
    MESSAGE_ID_ALGORITHM_REDUCE_TIME_NOSIE_VALUE,     // 时域降噪
    MESSAGE_ID_ALGORITHM_REDUCE_SPACE_NOISE_VALUE_1,   // 空域降噪系数1
    MESSAGE_ID_ALGORITHM_REDUCE_SPACE_NOISE_VALUE_2,   // 空域降噪系数2
    MESSAGE_ID_ALGORITHM_REDUCE_V_GRAIN_VALUE,           // 去竖纹系数
};

enum MESSAGE_ID_SENSOR_PAGE {
    MESSAGE_ID_SENSOR_RASEL = 601,
    MESSAGE_ID_SENSOR_INT,
    MESSAGE_ID_SENSOR_GAIN,
    MESSAGE_ID_SENSOR_HSSD,
    MESSAGE_ID_SENSOR_GFID,
    MESSAGE_ID_SENSOR_RC,
    MESSAGE_ID_SENSOR_RD,
    MESSAGE_ID_SENSOR_REF_RD,
    MESSAGE_ID_SENSOR_SKIM_NUC_STEP_ADJ,
    MESSAGE_ID_SENSOR_SKIM_GFID_REF_SETP_ADJ,
    MESSAGE_ID_SENSOR_VBUS,
    MESSAGE_ID_SENSOR_GSK_OP2,
    MESSAGE_ID_SENSOR_NMIDDLE,
    MESSAGE_ID_SENSOR_CSIZE,
    MESSAGE_ID_SENSOR_NUC_ENABLE,
    MESSAGE_ID_SENSOR_NUC_X_MAX,
    MESSAGE_ID_SENSOR_NUC_X_MIN,
    MESSAGE_ID_SENSOR_NUC_VALUE,
    MESSAGE_ID_SENSOR_NUC_DEFAULT,
    MESSAGE_ID_SENSOR_NUC_TEMP_MAX,
    MESSAGE_ID_SENSOR_AVERAGE_AD_VALUE,
    MESSAGE_ID_SENSOR_AD_VALUE,
    MESSAGE_ID_SENSOR_FOCUS_TEMP,
    MESSAGE_ID_SENSOR_RING_TEMP,
};

enum MESSAGE_ID_DATA_CONTROL_PAGE{
    MESSAGE_ID_DATA_CONTROL_UPDATE_BOOT = 701,  // boot
    MESSAGE_ID_DATA_CONTROL_UPDATE_APP,
    MESSAGE_ID_DATA_CONTROL_UPDATAE_PATTLE,
    MESSAGE_ID_DATA_CONTROL_CALIB_IN ,              // 内参
    MESSAGE_ID_DATA_CONTROL_CALIB_EX,              // 外参
    MESSAGE_ID_DATA_CONTROL_BAD_POINT_LIST,   // 坏点列表
    MESSAGE_ID_DATA_CONTROL_K_IMG,              // k图像
    MESSAGE_ID_DATA_CONTROL_BL_IMG,              // bl图像
    MESSAGE_ID_DATA_CONTROL_BH_IMG,              // bh图像
    MESSAGE_ID_DATA_CONTROL_SFFC_IMG,              // sffc图像
    MESSAGE_ID_DATA_CONTROL_ISP_VALUE,
    MESSAGE_ID_DATA_GET_BAD_POINT_LIST,
};

enum MESSAGE_ACTION
{
    MSG_ACTION_SET = 0,
    MSG_ACTION_REQUEST,
    MSG_ACTION_RESPONSE,
    MSG_ACTION_NOTIFY,
    MSG_ACTION_MAX
};

#endif // MESSAGEID_H
